name: Airflow-CI-Check

on: [push] # ทุกครั้งที่กด push งานขึ้นมา ให้เริ่มทำงานทันที

jobs:
  check-my-code:
    runs-on: ubuntu-latest # ใช้เครื่องคอมฟรีของ GitHub (Linux)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # 1. ไปดึงโค้ดจาก Git ของคุณออกมา

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 2. เตรียมลง Python ให้พร้อม

      - name: Install Linting Tool
        run: pip install ruff # 3. ติดตั้งเครื่องมือตรวจคำผิด (Ruff)

      - name: Run Syntax Check
        run: ruff check . # 4. สั่งตรวจทั้งโฟลเดอร์ว่ามีตรงไหนเขียน Python ผิดไหม